gazetteers = {
    'gaz_deviceTypes': {'devicetype', 'device', 'pc', 'devices', 'computer',
                        'computers', 'laptop', 'laptops', 'smartphone',
                        'smartphones', 'phone', 'phones', 'cellphone',
                        'mobile', 'mobiles', 'tablet', 'tablets', 'notebook',
                        'notebooks'},
    'gaz_referralDomain': {'domain', 'domains', 'referraldomain', 'referrals',
                           'referral', 'domains', 'referraldomains',
                           'website', 'site', 'websites', 'facebook',
                           'facebook.com', 'brunel.nl', 'fb', 'instagram',
                           'instagram.com', 'twitter', 'twitter.com', 'google',
                           'google.com', 'google.be', 'linkedin',
                           'linkedin.com'},
    'gaz_cfCountry': {'country', 'place', 'places', 'destinations',
                      'nationality', 'countries', 'where', 'foreign',
                      'destination', 'belgium', 'belgian', 'netherlands',
                      'dutch', 'germany', 'german', 'germans', 'french',
                      'Danish', 'DK' 'france', 'england', 'uk', 'britain',
                      'britains', 'united', 'kingdom', 'spain',
                      'spanish', 'italy', 'italian', 'italians', 'sweden',
                      'swedish', 'norway', 'norwegian', 'australia',
                      'australians', 'u.s.', 'american', 'america',
                      'americans', 'states', 'canada', 'canadian', 'japan',
                      'japanese', 'vietnam', 'vietnamese', 'china', 'chinese',
                      'russian', 'russia', 'mexico', 'mexican',
                      'denmark', 'danish', 'us', 'poland', 'polish',
                      'portugal', 'portuguese', 'portugese', 'brazil',
                      'brazilian', 'panama'},
    'gaz_browserTypes': {'browser', 'browsers', 'browsertype', 'mozilla',
                         'firefox', 'internet', 'explorer', 'safari',
                         'oracle', 'chrome', 'edge'},
    'gaz_languages': {'language', 'languages', 'english', 'dutch', 'canadian',
                      'spanish', 'japanese', 'french', 'german',
                      'russian', 'chinese', 'vietnamese', 'italian', 'swedish',
                      'norwegian', 'danish', 'portuguese'},
    'gaz_deviceBrands': {'devicebrand', 'brand', 'brands', 'iphone', 'ipad',
                         'macbook', 'sony', 'samsung', 'apple',
                         'huawei', 'blackberry', 'acer', 'asus', 'hp', 'dell'},
    'gaz_deviceTypes': {'devicetype', 'device', 'pc', 'computer', 'computers',
                        'laptop', 'laptops', 'smartphone',
                        'smartphones', 'phone', 'phones', 'cellphone',
                        'mobile', 'mobiles', 'tablet', 'tablets', 'notebook',
                        'notebooks'},
    'gaz_referralDomain': {'website', 'site', 'referring', 'referrer',
                           'domain', 'referraldomain', 'referrals', 'referral',
                           'domains', 'referraldomains', 'facebook',
                           'facebook.com', 'brunel.nl', 'fb', 'instagram',
                           'instagram.com', 'twitter', 'twitter.com', 'google',
                           'google.com', 'google.be', 'linkedin',
                           'linkedin.com'},
    'gaz_cfCountry': {'country', 'location', 'place', 'places', 'destinations',
                      'nationality', 'countries', 'where',
                      'foreign', 'destination', 'belgium', 'belgian',
                      'netherlands', 'dutch', 'germany', 'german', 'germans',
                      'french', 'france', 'england', 'uk', 'britain',
                      'britains', 'united', 'kingdom', 'spain', 'spanish',
                      'italy', 'italian', 'italians', 'sweden', 'swedish',
                      'norway', 'norwegian', 'australia',
                      'australians', 'u.s.', 'american', 'america',
                      'americans', 'states', 'canada', 'canadian', 'japan',
                      'japanese', 'vietnam', 'vietnamese', 'china', 'chinese',
                      'russian', 'russia', 'mexico', 'mexican',
                      'denmark', 'danish', 'poland', 'polish', 'portugal',
                      'portuguese', 'portugese', 'brazil', 'brazilian',
                      'panama'},
    'gaz_browserTypes': {'browser', 'browsers', 'browsertype', 'mozilla',
                         'firefox', 'internet', 'explorer', 'safari',
                         'oracle', 'chrome', 'edge'},
    'gaz_languages': {'language', 'languages', 'english', 'dutch', 'canadian',
                      'spanish', 'japanese', 'french', 'german',
                      'russian', 'chinese', 'vietnamese', 'italian', 'swedish',
                      'norwegian', 'danish', 'portuguese'},
    'gaz_deviceBrands': {'devicebrand', 'brand', 'brands', 'iphone', 'ipad',
                         'macbook', 'sony', 'samsung', 'apple',
                         'huawei', 'blackberry', 'acer', 'asus', 'hp', 'dell',
                         'apple', 'samsung', 'generic', 'generic_android',
                         'motorola', 'lg', 'huawei', 'htc', 'nokia',
                         'xiaomi', 'lenovo', 'asus', 'sony', 'microsoft',
                         'amazon', 'infinix', 'sonyericsson', 'coolpad',
                         'spider', 'zte', 'alcatel', 'vivo', 'thl', 'lava',
                         'micromax', 'zopo', 'panasonic', 'archos',
                         'cubot'},
    'gaz_osTypes': {'system', 'operating', 'os', 'systems', 'operatingsystem',
                    'ubuntu', 'linux', 'windows', 'ios', 'iOS',
                    'android'},
    'gaz_referralType': {'referral', 'type', 'referraltypes', 'referraltype',
                         'internal', 'email', 'mail', 'social', 'media',
                         'search', 'engine', 'direct', 'advertising',
                         'advertisement', 'android', 'app'},
    'gaz_touch': {'touch', 'screen', 'touchscreen'},
    'gaz_adblock': {'ad', 'block', 'adblock', 'adblocker', 'adblocking'},
    'gaz_visitorId': {'traffic', 'person', 'persons', 'user', 'session',
                      'sessions', 'people', 'users', 'guests',
                      'visitors', 'visited'},
    'gaz_visitTime': {'duration', 'durations', 'length', 'minutes', 'seconds',
                      'minute', 'visittime', 'visittimes', 'mins', 'secs',
                      'long'},
    'gaz_pagesPerVisitor': {'one', 'single', 'homepage'},
    'gaz_bounce': {'fast', 'bounced'}
}
